#!/bin/bash
set -e

echo "Installing ruckig from nickswalker/ruckig@dev..."
TMP_DIR="$(mktemp -d /var/tmp/tmp.XXXXXXXXXX)"
git clone --depth 1 --branch dev https://github.com/nickswalker/ruckig.git "${TMP_DIR}"
cd "${TMP_DIR}"
mkdir build
cd build
cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=OFF -DBUILD_TESTS=OFF -DBUILD_PYTHON_MODULE=OFF -DBUILD_CLOUD_CLIENT=OFF
make -j "$(nproc)"
sudo make install || make install
cd /
rm -rf "${TMP_DIR}"
echo "ruckig installed successfully"
